/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signals1.gui.radar;

import signals1.radar.RadarParameters;
import signals1.tools.exceptions.InputValidationException;

/**
 *
 * @author marr
 */
public class RadarInputPanel extends javax.swing.JPanel {

    /**
     * Creates new form RadarInputPanel
     */
    public RadarInputPanel() {
        initComponents();
    }

    public RadarParameters getParameters() throws InputValidationException {
        RadarParameters params;
        try {
            double firstCompomentPeriod = Double.parseDouble(jTextPeriod1.getText()) / 1000;
            double secondCompomentPeriod = Double.parseDouble(jTextPeriod2.getText()) / 1000;
            int samplingRate = Integer.parseInt(jTextSamplingRate.getText());
            double buforLength = Double.parseDouble(jTextBuferSize.getText()) / 1000;
            double initialDistance = Double.parseDouble(jTextDistance.getText());
            double velocity = Double.parseDouble(jTextVelocity.getText());
            double interval = Double.parseDouble(jTextInterval.getText()) / 1000;
            double waveSpeed = Double.parseDouble(jTextWaveSpeed.getText());
            params = new RadarParameters(firstCompomentPeriod, secondCompomentPeriod, samplingRate, buforLength, initialDistance, velocity, interval, waveSpeed);
        } catch (Exception ex) {
            throw new InputValidationException();
        }
        return params;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextPeriod1 = new javax.swing.JTextField();
        jTextPeriod2 = new javax.swing.JTextField();
        jTextSamplingRate = new javax.swing.JTextField();
        jTextBuferSize = new javax.swing.JTextField();
        jTextDistance = new javax.swing.JTextField();
        jTextVelocity = new javax.swing.JTextField();
        jTextInterval = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextWaveSpeed = new javax.swing.JTextField();

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Okres pierwszej składowej sygnału [ms]");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Okres drugiej składowej sygnału [ms]");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Częstotliwość próbkowania [Hz]");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Długość bufora [ms]");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Odległość początkowa [m]");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Prędkość względem nadajnika [m/s]");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Odstęp pomiędzy pomiarami [ms]");

        jTextPeriod1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextPeriod1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPeriod1.setText("22");

        jTextPeriod2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextPeriod2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPeriod2.setText("15");
        jTextPeriod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPeriod2ActionPerformed(evt);
            }
        });

        jTextSamplingRate.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextSamplingRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextSamplingRate.setText("12000");

        jTextBuferSize.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextBuferSize.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextBuferSize.setText("400");

        jTextDistance.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextDistance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextDistance.setText("500");

        jTextVelocity.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextVelocity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextVelocity.setText("300");

        jTextInterval.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextInterval.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextInterval.setText("1000");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Prędkość rozchodzenia się fali [m/s]");

        jTextWaveSpeed.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTextWaveSpeed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextWaveSpeed.setText("300000");
        jTextWaveSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextWaveSpeedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextDistance)
                    .addComponent(jTextBuferSize)
                    .addComponent(jTextSamplingRate)
                    .addComponent(jTextPeriod2)
                    .addComponent(jTextPeriod1)
                    .addComponent(jTextInterval)
                    .addComponent(jTextVelocity)
                    .addComponent(jTextWaveSpeed, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPeriod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPeriod2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSamplingRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextBuferSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextWaveSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextWaveSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextWaveSpeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextWaveSpeedActionPerformed

    private void jTextPeriod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPeriod2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPeriod2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextBuferSize;
    private javax.swing.JTextField jTextDistance;
    private javax.swing.JTextField jTextInterval;
    private javax.swing.JTextField jTextPeriod1;
    private javax.swing.JTextField jTextPeriod2;
    private javax.swing.JTextField jTextSamplingRate;
    private javax.swing.JTextField jTextVelocity;
    private javax.swing.JTextField jTextWaveSpeed;
    // End of variables declaration//GEN-END:variables
}
