/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signals1.gui;

import signals1.gui.radar.RadarWindow;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.apache.commons.math3.complex.Complex;
import signals1.gui.inputForms.SineInputPanel;
import signals1.gui.inputForms.SquareInputPanel;
import signals1.gui.tables.DiscreteSignalTableModel;
import signals1.gui.tables.VirtualSignalsTableModel;
import signals1.operations.AmplitudeCalculator;
import signals1.continuousSignals.abstracts.NonPeriodicSignals;
import signals1.continuousSignals.abstracts.PeriodicSignals;
import signals1.continuousSignals.abstracts.AbstractSignal;
import signals1.converter.Converters;
import signals1.converter.D2AConverterService;
import signals1.discreteSignals.DerivedSignal;
import signals1.discreteSignals.abstracts.DiscreteSignal;
import signals1.discreteSignals.NonPeriodicDiscreteSignal;
import signals1.discreteSignals.PeriodicDiscreteSignal;
import signals1.fourier.GGFourierTransform;
import signals1.gui.inputForms.InputPanel;
import signals1.gui.inputForms.NoiseInputPanel;
import signals1.gui.radar.RadarInputPanel;
import signals1.operations.Convolution;
import signals1.operations.Correlation;
import signals1.operations.filters.BandPassFIRFilter;
import signals1.operations.filters.FIRFilter;
import signals1.operations.filters.HighPassFIRFilter;
import signals1.operations.filters.LowPassFIRFilter;
import signals1.operations.windows.Windows;
import signals1.tools.DiscretetSignalsContainer;
import signals1.radar.RadarParameters;
import signals1.tools.SignalContainer;
import signals1.tools.constatns.Quantizers;
import signals1.tools.exceptions.InputValidationException;
import signals1.tools.exceptions.NotPowerOfTwoException;
import signals1.tools.exceptions.NotSameSamplinRateExpcetion;

/**
 *
 * @author marr
 */
public class MainWindow extends javax.swing.JFrame {

    private final Dimension inputFormDimension = new Dimension(400, 320);
    private SineInputPanel sineInputPanel;
    private SquareInputPanel squareInputPanel;
    private NoiseInputPanel noiseInputPanel;
    private RadarInputPanel radarInputPanel;
    private final SignalContainer signalContainer = SignalContainer.getInstance();
    private final DiscretetSignalsContainer disSignalContainer = DiscretetSignalsContainer.getInstance();
    private final VirtualSignalsTableModel virtulTableModel = new VirtualSignalsTableModel();
    private final DiscreteSignalTableModel discreteTableModel = new DiscreteSignalTableModel();
    private FileChooserDialog fileDialog;
    private static MainWindow instance = null;

    /**
     * Creates new form NewJFrame
     */
    public MainWindow() {

        InitLookAndFeel();
        initComponents();
        initInputForms();
        setUpVirtualTable();
        setUpDiscreteTable();
        fileDialog = new FileChooserDialog(this, true);
        fileDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                fileDialog.setVisible(false);
            }
        });
        instance = this;
    }

    public static MainWindow GetInstance() {
        return instance;
    }

    private static void InitLookAndFeel() {
        String lookAndFeel = null;
        lookAndFeel = UIManager.getSystemLookAndFeelClassName();
        try {
            UIManager.setLookAndFeel(lookAndFeel);
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException e) {
        } catch (Exception e) {
            //TODO :)
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPaneInputTabs = new javax.swing.JTabbedPane();
        jPanelSineSignals = new javax.swing.JPanel();
        jPanelSquareSignals = new javax.swing.JPanel();
        jPanelNoiseSignals = new javax.swing.JPanel();
        jPanelRadar = new javax.swing.JPanel();
        jButtonGenerateSignal = new javax.swing.JButton();
        jSliderHistNo = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVirtual = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextSamplingRate = new javax.swing.JTextField();
        jButtonSampling = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDiscrete = new javax.swing.JTable();
        jButtonShowSignal = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jButtonClearVirtualTable = new javax.swing.JButton();
        jButtonClearDiscreteTable1 = new javax.swing.JButton();
        jCheckBoxOperationOrder = new javax.swing.JCheckBox();
        jComboQType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboQuantBits = new javax.swing.JComboBox<>();
        jButtonSampling1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboConvType1 = new javax.swing.JComboBox<>();
        jButtonCompare = new javax.swing.JButton();
        jButtonAddSignals = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonConvolution = new javax.swing.JButton();
        jButtonCorrelation = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboWindow = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboFIRFilter = new javax.swing.JComboBox<>();
        jTextFilterOrder = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextSamplingRate3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lowCutoffFreqTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        highCutoffReqTextField = new javax.swing.JTextField();
        jButtonConvolution1 = new javax.swing.JButton();
        jCheckBoxFFTSignalOperation = new javax.swing.JCheckBox();
        saveSignal = new javax.swing.JButton();
        loadSignal = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sygnały");
        setResizable(false);

        jPaneInputTabs.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPaneInputTabs.setPreferredSize(new java.awt.Dimension(420, 320));
        jPaneInputTabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jPaneInputTabsStateChanged(evt);
            }
        });

        jPanelSineSignals.setPreferredSize(inputFormDimension);

        javax.swing.GroupLayout jPanelSineSignalsLayout = new javax.swing.GroupLayout(jPanelSineSignals);
        jPanelSineSignals.setLayout(jPanelSineSignalsLayout);
        jPanelSineSignalsLayout.setHorizontalGroup(
            jPanelSineSignalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        jPanelSineSignalsLayout.setVerticalGroup(
            jPanelSineSignalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        jPaneInputTabs.addTab("Sygnały sinusoidalne", jPanelSineSignals);

        javax.swing.GroupLayout jPanelSquareSignalsLayout = new javax.swing.GroupLayout(jPanelSquareSignals);
        jPanelSquareSignals.setLayout(jPanelSquareSignalsLayout);
        jPanelSquareSignalsLayout.setHorizontalGroup(
            jPanelSquareSignalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        jPanelSquareSignalsLayout.setVerticalGroup(
            jPanelSquareSignalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        jPaneInputTabs.addTab("Sygnały prostokątne", jPanelSquareSignals);

        javax.swing.GroupLayout jPanelNoiseSignalsLayout = new javax.swing.GroupLayout(jPanelNoiseSignals);
        jPanelNoiseSignals.setLayout(jPanelNoiseSignalsLayout);
        jPanelNoiseSignalsLayout.setHorizontalGroup(
            jPanelNoiseSignalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        jPanelNoiseSignalsLayout.setVerticalGroup(
            jPanelNoiseSignalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        jPaneInputTabs.addTab("Szumy", jPanelNoiseSignals);

        javax.swing.GroupLayout jPanelRadarLayout = new javax.swing.GroupLayout(jPanelRadar);
        jPanelRadar.setLayout(jPanelRadarLayout);
        jPanelRadarLayout.setHorizontalGroup(
            jPanelRadarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        jPanelRadarLayout.setVerticalGroup(
            jPanelRadarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        jPaneInputTabs.addTab("Radar", jPanelRadar);

        jButtonGenerateSignal.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jButtonGenerateSignal.setText("Generuj Sygnał Pseudociągły");
        jButtonGenerateSignal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateSignalActionPerformed(evt);
            }
        });

        jSliderHistNo.setMajorTickSpacing(5);
        jSliderHistNo.setMaximum(20);
        jSliderHistNo.setMinimum(5);
        jSliderHistNo.setMinorTickSpacing(5);
        jSliderHistNo.setPaintLabels(true);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("liczba przedziałów histogramu");

        jTableVirtual.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTableVirtual.setModel(virtulTableModel);
        jTableVirtual.setDragEnabled(true);
        jTableVirtual.setRowHeight(18);
        jTableVirtual.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableVirtual);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setText("Wygenerowane sygnały pseudociągłe");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Częstotliwośc próbkowania[Hz]");

        jTextSamplingRate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextSamplingRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextSamplingRate.setText("1024");

        jButtonSampling.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jButtonSampling.setText("Próbkuj sygnał");
        jButtonSampling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSamplingActionPerformed(evt);
            }
        });

        jTableDiscrete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTableDiscrete.setModel(discreteTableModel);
        jTableDiscrete.setRowHeight(18);
        jTableDiscrete.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane2.setViewportView(jTableDiscrete);

        jButtonShowSignal.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jButtonShowSignal.setText("Wyświetl sygnał");
        jButtonShowSignal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowSignalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Próbkowanie Sygnałów");

        jButtonClearVirtualTable.setText("Wyczyść");
        jButtonClearVirtualTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearVirtualTableActionPerformed(evt);
            }
        });

        jButtonClearDiscreteTable1.setText("Wyczyść");
        jButtonClearDiscreteTable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearDiscreteTable1ActionPerformed(evt);
            }
        });

        jCheckBoxOperationOrder.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxOperationOrder.setText("Odwróć kolejność");

        jComboQType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboQType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brak kwantyzacji", "Kwantyzacja równomierna z obcięciem", "Kwantyzacja równomierna z zaokrąglaniem" }));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("Typ kwantyzacji");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Liczba bitów kwantyzacji");

        jComboQuantBits.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboQuantBits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "4", "6", "8", "12", "16", " " }));
        jComboQuantBits.setSelectedIndex(4);
        jComboQuantBits.setToolTipText("");

        jButtonSampling1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jButtonSampling1.setText("Konwertuj");
        jButtonSampling1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSampling1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("Okno");

        jComboConvType1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboConvType1.setModel(new DefaultComboBoxModel(Converters.Types.values()));

        jButtonCompare.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButtonCompare.setText("Porównaj sygnały");
        jButtonCompare.setActionCommand("loadSignal");
        jButtonCompare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompareActionPerformed(evt);
            }
        });

        jButtonAddSignals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonAddSignals.setText("+");
        jButtonAddSignals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSignalsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Operacje na sygnałach");

        jButtonConvolution.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonConvolution.setText("SPLOT");
        jButtonConvolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvolutionActionPerformed(evt);
            }
        });

        jButtonCorrelation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCorrelation.setText("KORELACJA");
        jButtonCorrelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCorrelationActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Filtry");

        jComboWindow.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboWindow.setModel(new DefaultComboBoxModel(Windows.Types.values()));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setText("Typ konwersji");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setText("Filtr");

        jComboFIRFilter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboFIRFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolnoprzepustowy", "Górnoprzepustowy", "Pasmowy" }));

        jTextFilterOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFilterOrder.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFilterOrder.setText("1024");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setText("Rząd Filtru [ilość próbek]");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setText("Częstotliwośc próbkowania[Hz]");

        jTextSamplingRate3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextSamplingRate3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextSamplingRate3.setText("1024");

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel15.setText("Częstotliwośc odcięcia niskiego [Hz]");

        lowCutoffFreqTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lowCutoffFreqTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lowCutoffFreqTextField.setText("100");

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel16.setText("Częstotliwośc odcięcia wysokiego [Hz]");

        highCutoffReqTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        highCutoffReqTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        highCutoffReqTextField.setText("500");

        jButtonConvolution1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonConvolution1.setText("Utwórz Filtr");
        jButtonConvolution1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvolution1ActionPerformed(evt);
            }
        });

        jCheckBoxFFTSignalOperation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxFFTSignalOperation.setText("Transformaty");

        saveSignal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        saveSignal.setText("Zapisz");
        saveSignal.setActionCommand("saveSignal");
        saveSignal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSignalActionPerformed(evt);
            }
        });

        loadSignal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        loadSignal.setText("Odczytaj");
        loadSignal.setActionCommand("loadSignal");
        loadSignal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSignalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextSamplingRate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonClearDiscreteTable1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jComboQuantBits, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jButtonSampling)
                                            .addGap(12, 12, 12))
                                        .addComponent(jComboQType, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonSampling1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboConvType1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSliderHistNo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(jButtonAddSignals, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCheckBoxFFTSignalOperation)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButtonConvolution, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jButtonCorrelation, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButtonShowSignal, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                                .addComponent(jCheckBoxOperationOrder)
                                                .addComponent(jButtonCompare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(saveSignal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(loadSignal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPaneInputTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonGenerateSignal, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(177, 177, 177)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonClearVirtualTable, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jComboFIRFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel14))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jComboWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextFilterOrder)
                                                .addComponent(jTextSamplingRate3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(161, 161, 161)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel15))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addComponent(jLabel16)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(13, 13, 13)
                                            .addComponent(lowCutoffFreqTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(highCutoffReqTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(90, 90, 90)
                                            .addComponent(jButtonConvolution1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPaneInputTabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jButtonGenerateSignal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClearVirtualTable)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFilterOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextSamplingRate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboFIRFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jButtonConvolution1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lowCutoffFreqTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(highCutoffReqTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSamplingRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(149, 149, 149))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jComboQType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jComboConvType1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(1, 1, 1)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jComboQuantBits, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGap(12, 12, 12)
                                                    .addComponent(jButtonSampling, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonSampling1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxFFTSignalOperation)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jButtonConvolution, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonCorrelation, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButtonAddSignals, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(9, 9, 9)
                                .addComponent(jCheckBoxOperationOrder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCompare, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonShowSignal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveSignal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loadSignal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jSliderHistNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClearDiscreteTable1)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerateSignalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateSignalActionPerformed

        switch (jPaneInputTabs.getSelectedIndex()) {
            case 0:
                addDiscreteSignal(sineInputPanel);
                break;
            case 1:
                addDiscreteSignal(squareInputPanel);
                break;
            case 2:
                addDiscreteSignal(noiseInputPanel);
                break;
            case 3: {
                try {
                    RadarParameters param = radarInputPanel.getParameters();
                    RadarWindow radarWindow = new RadarWindow(param);
                    radarWindow.setVisible(true);
                } catch (InputValidationException ex) {
                    JOptionPane.showMessageDialog(this, "Walidacja danych wejściowych nie powiodła się", "Błąd", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

        }
    }//GEN-LAST:event_jButtonGenerateSignalActionPerformed

    private void jButtonSamplingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSamplingActionPerformed
        int selectedVirtualSignal = jTableVirtual.getSelectedRow();
        if (selectedVirtualSignal < 0) {
            return;
        }
        int sampling = Integer.parseInt(jTextSamplingRate.getText());
        AbstractSignal virtualSignal = signalContainer.getById(getIdFromVirtualTable(selectedVirtualSignal));
        if (virtualSignal == null) {
            return;
        }
        if (virtualSignal instanceof PeriodicSignals) {
            disSignalContainer.add(new PeriodicDiscreteSignal((PeriodicSignals) virtualSignal, sampling, Quantizers.getQuantizer(jComboQType.getSelectedIndex(), Integer.parseInt((String) jComboQuantBits.getSelectedItem()))));
        } else if (virtualSignal instanceof NonPeriodicSignals) {
            disSignalContainer.add(new NonPeriodicDiscreteSignal((NonPeriodicSignals) virtualSignal, sampling, Quantizers.getQuantizer(jComboQType.getSelectedIndex(), Integer.parseInt((String) jComboQuantBits.getSelectedItem()))));
        }
        discreteTableModel.fireTableDataChanged();
    }//GEN-LAST:event_jButtonSamplingActionPerformed

    private void jButtonShowSignalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowSignalActionPerformed
        int selectedDiscreteSignal = jTableDiscrete.getSelectedRow();
        if (selectedDiscreteSignal < 0) {
            return;
        }
        DiscreteSignal signal = disSignalContainer.getById(getIdFromDiscreteTable(selectedDiscreteSignal));
        if (signal == null) {
            return;
        }
        OutputPanelAmplitude amPanel = new OutputPanelAmplitude(signal);
        OutputPanelModAndPhase modAndShiftPanel = new OutputPanelModAndPhase(signal);
        OutputPanelFrequency freqPanel = new OutputPanelFrequency(signal);
        HistogramPanel hisPanel = new HistogramPanel(signal.getHistogram(jSliderHistNo.getValue()), jSliderHistNo.getValue());
        HistogramPanel hisModAndShiftPanel = new HistogramPanel(signal.getHistogramModAndShift(jSliderHistNo.getValue()), jSliderHistNo.getValue());
        OutputWindow outputWindow = new OutputWindow(signal, amPanel, hisPanel, modAndShiftPanel, hisModAndShiftPanel, freqPanel);
        outputWindow.setVisible(true);
    }//GEN-LAST:event_jButtonShowSignalActionPerformed

    private void jButtonClearVirtualTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearVirtualTableActionPerformed
        signalContainer.clear();
        virtulTableModel.fireTableDataChanged();
    }//GEN-LAST:event_jButtonClearVirtualTableActionPerformed

    private void jButtonClearDiscreteTable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearDiscreteTable1ActionPerformed
        disSignalContainer.clear();
        discreteTableModel.fireTableDataChanged();
    }//GEN-LAST:event_jButtonClearDiscreteTable1ActionPerformed

    private void jButtonSampling1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSampling1ActionPerformed
        int selectedDiscreteSignal = jTableDiscrete.getSelectedRow();
        if (selectedDiscreteSignal < 0) {
            return;
        }
        DiscreteSignal signal = disSignalContainer.getById(getIdFromDiscreteTable(selectedDiscreteSignal));
        if (signal == null) {
            return;
        }

        int sampling = Integer.parseInt(jTextSamplingRate.getText());

        D2AConverterService service = new D2AConverterService(new Converters((Converters.Types) jComboConvType1.getSelectedItem()).getConverter(), signal, sampling);
        addDiscreteSignal(service.getOutput());

    }//GEN-LAST:event_jButtonSampling1ActionPerformed

    private void jButtonCompareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompareActionPerformed
        if (jTableDiscrete.getSelectedRowCount() != 2) {
            return;
        }
        int[] signals = new int[2];
        if (jCheckBoxOperationOrder.isSelected()) {
            signals[0] = getIdFromDiscreteTable(jTableDiscrete.getSelectedRows()[0]);
            signals[1] = getIdFromDiscreteTable(jTableDiscrete.getSelectedRows()[1]);
        } else {
            signals[1] = getIdFromDiscreteTable(jTableDiscrete.getSelectedRows()[0]);
            signals[0] = getIdFromDiscreteTable(jTableDiscrete.getSelectedRows()[1]);

        }
        CompareDialog compare = new CompareDialog(signals[0], signals[1]);
        compare.setVisible(true);

    }//GEN-LAST:event_jButtonCompareActionPerformed

    private void jButtonAddSignalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSignalsActionPerformed
        DiscreteSignal[] signals = getSignalsForCalculation();
        if (signals != null) {
            try {
                disSignalContainer.add(AmplitudeCalculator.AddSignals(signals[0], signals[1]));
                discreteTableModel.fireTableDataChanged();
            } catch (NotSameSamplinRateExpcetion ex) {
                JOptionPane.showMessageDialog(this, "Wybierz sygnały o takiej samej częstotliwości próbkowania", "Błąd", JOptionPane.ERROR_MESSAGE);
            } finally {
                discreteTableModel.fireTableDataChanged();
            }
        }
    }//GEN-LAST:event_jButtonAddSignalsActionPerformed

    private void jButtonConvolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvolutionActionPerformed
        DiscreteSignal[] signals = getSignalsForCalculation();
        if (signals != null) {
            if (jCheckBoxFFTSignalOperation.isSelected()) {
                try {
                    disSignalContainer.add(Convolution.CalculateConvolutions(signals[0].getFourierTransformate(), 
                                                                             signals[1].getFourierTransformate(), 
                                                                             signals[0].getSamplingRate(), 
                                                                             signals[0].getStartTime(), 
                                                                             signals[0].getAmplitude()));
                } catch (NotPowerOfTwoException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                disSignalContainer.add(Convolution.CalculateConvolutions(signals[0], signals[1]));
            }

            discreteTableModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_jButtonConvolutionActionPerformed

    private void jButtonCorrelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCorrelationActionPerformed
        DiscreteSignal[] signals = getSignalsForCalculation();
        if (signals != null) {
            disSignalContainer.add(Correlation.CalculateCorrelation(signals[0], signals[1]));
            discreteTableModel.fireTableDataChanged();
        }
    }//GEN-LAST:event_jButtonCorrelationActionPerformed

    private void jPaneInputTabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jPaneInputTabsStateChanged
        switch (jPaneInputTabs.getSelectedIndex()) {
            case 3:
                jButtonGenerateSignal.setText("Dokonaj pomiaru");
                break;
            default:
                jButtonGenerateSignal.setText("Generuj Sygnał Pseudociągły");
                break;
        }
    }//GEN-LAST:event_jPaneInputTabsStateChanged

    private void jButtonConvolution1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvolution1ActionPerformed

        double sampling = Double.parseDouble(jTextSamplingRate3.getText());
        double lowCutoffFreq = Double.parseDouble(lowCutoffFreqTextField.getText());
        double highCutoffReq = Double.parseDouble(highCutoffReqTextField.getText());
        int order = Integer.parseInt(jTextFilterOrder.getText());
        int firIndex = jComboFIRFilter.getSelectedIndex();
        FIRFilter filter = null;
        switch (firIndex) {
            case 0:
                filter = new LowPassFIRFilter(new Windows((Windows.Types) jComboWindow.getSelectedItem()).getWindows(), order, lowCutoffFreq, sampling);
                break;
            case 1:
                filter = new HighPassFIRFilter(new Windows((Windows.Types) jComboWindow.getSelectedItem()).getWindows(), order, highCutoffReq, sampling);
                break;
            default:
                filter = new BandPassFIRFilter(new Windows((Windows.Types) jComboWindow.getSelectedItem()).getWindows(), order, lowCutoffFreq, highCutoffReq, sampling);
        }
        Complex[] values = filter.getFilter();

        DerivedSignal signal = new DerivedSignal(values, (int) sampling, 0, 1);
        addDiscreteSignal(signal);

    }//GEN-LAST:event_jButtonConvolution1ActionPerformed

    private void saveSignalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSignalActionPerformed
        int selectedDiscreteSignal = jTableDiscrete.getSelectedRow();
        if (selectedDiscreteSignal < 0) {
            return;
        }
        fileDialog.setDialogType(JFileChooser.SAVE_DIALOG);
        DiscreteSignal selected = getSelectedSignal();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Wybierz sygnał do zapisu", "Błąd", JOptionPane.ERROR_MESSAGE);
        } else {
            fileDialog.setSignal(selected);
            fileDialog.setAction(evt.getActionCommand());
            fileDialog.setVisible(true);
        }
    }//GEN-LAST:event_saveSignalActionPerformed

    private void loadSignalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSignalActionPerformed
        fileDialog.setDialogType(JFileChooser.OPEN_DIALOG);
        fileDialog.setSignal(null);
        fileDialog.setAction(evt.getActionCommand());
        fileDialog.setVisible(true);
    }//GEN-LAST:event_loadSignalActionPerformed

    private void initInputForms() {
        sineInputPanel = new SineInputPanel(inputFormDimension);
        squareInputPanel = new SquareInputPanel(inputFormDimension);
        noiseInputPanel = new NoiseInputPanel(inputFormDimension);
        radarInputPanel = new RadarInputPanel();

        jPanelSineSignals.setLayout(new java.awt.BorderLayout());
        jPanelSineSignals.add(sineInputPanel, BorderLayout.CENTER);
        jPanelSquareSignals.setLayout(new java.awt.BorderLayout());
        jPanelSquareSignals.add(squareInputPanel, BorderLayout.CENTER);
        jPanelNoiseSignals.setLayout(new java.awt.BorderLayout());
        jPanelNoiseSignals.add(noiseInputPanel, BorderLayout.CENTER);
        jPanelRadar.setLayout(new java.awt.BorderLayout());
        jPanelRadar.add(radarInputPanel, BorderLayout.CENTER);

        jPanelSquareSignals.validate();
        jPanelRadar.validate();
        jPanelSineSignals.validate();
        jPanelNoiseSignals.validate();

    }

    private void setUpVirtualTable() {
        jTableVirtual.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTableVirtual.getColumnModel().getColumn(1).setPreferredWidth(175);
        jTableVirtual.getColumnModel().getColumn(2).setPreferredWidth(115);
        jTableVirtual.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTableVirtual.getColumnModel().getColumn(4).setPreferredWidth(60);
        jTableVirtual.getColumnModel().getColumn(5).setPreferredWidth(60);
        jTableVirtual.getColumnModel().getColumn(5).setPreferredWidth(95);
    }

    private void setUpDiscreteTable() {
        jTableDiscrete.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTableDiscrete.getColumnModel().getColumn(1).setPreferredWidth(175);
        jTableDiscrete.getColumnModel().getColumn(2).setPreferredWidth(115);
        jTableDiscrete.getColumnModel().getColumn(3).setPreferredWidth(90);
        jTableDiscrete.getColumnModel().getColumn(4).setPreferredWidth(60);
        jTableDiscrete.getColumnModel().getColumn(5).setPreferredWidth(60);
    }

    private int getIdFromDiscreteTable(int row) {
        return (int) jTableDiscrete.getModel().getValueAt(row, 0);
    }

    private int getIdFromVirtualTable(int row) {
        return (int) jTableVirtual.getModel().getValueAt(row, 0);
    }

    private DiscreteSignal getSelectedSignal() {
        DiscreteSignal signal = disSignalContainer.getById(getIdFromDiscreteTable(jTableDiscrete.getSelectedRows()[0]));
        return signal;
    }
    
    private DiscreteSignal[] getSignalsForCalculation() {
        if (jTableDiscrete.getSelectedRowCount() != 2) {
            return null;
        }
        DiscreteSignal[] signals = new DiscreteSignal[2];
        if (jCheckBoxOperationOrder.isSelected()) {
            signals[0] = disSignalContainer.getById(getIdFromDiscreteTable(jTableDiscrete.getSelectedRows()[0]));
            signals[1] = disSignalContainer.getById(getIdFromDiscreteTable(jTableDiscrete.getSelectedRows()[1]));
        } else {
            signals[1] = disSignalContainer.getById(getIdFromDiscreteTable(jTableDiscrete.getSelectedRows()[0]));
            signals[0] = disSignalContainer.getById(getIdFromDiscreteTable(jTableDiscrete.getSelectedRows()[1]));

        }
        return signals;
    }

    private void addDiscreteSignal(InputPanel inputPanel) {
        AbstractSignal signal = inputPanel.getSingal();
        if (signal != null) {
            signalContainer.add(signal);
            virtulTableModel.fireTableDataChanged();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField highCutoffReqTextField;
    private javax.swing.JButton jButtonAddSignals;
    private javax.swing.JButton jButtonClearDiscreteTable1;
    private javax.swing.JButton jButtonClearVirtualTable;
    private javax.swing.JButton jButtonCompare;
    private javax.swing.JButton jButtonConvolution;
    private javax.swing.JButton jButtonConvolution1;
    private javax.swing.JButton jButtonCorrelation;
    private javax.swing.JButton jButtonGenerateSignal;
    private javax.swing.JButton jButtonSampling;
    private javax.swing.JButton jButtonSampling1;
    private javax.swing.JButton jButtonShowSignal;
    private javax.swing.JCheckBox jCheckBoxFFTSignalOperation;
    private javax.swing.JCheckBox jCheckBoxOperationOrder;
    private javax.swing.JComboBox<String> jComboConvType1;
    private javax.swing.JComboBox<String> jComboFIRFilter;
    private javax.swing.JComboBox<String> jComboQType;
    private javax.swing.JComboBox<String> jComboQuantBits;
    private javax.swing.JComboBox<String> jComboWindow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jPaneInputTabs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelNoiseSignals;
    private javax.swing.JPanel jPanelRadar;
    private javax.swing.JPanel jPanelSineSignals;
    private javax.swing.JPanel jPanelSquareSignals;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSliderHistNo;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableDiscrete;
    private javax.swing.JTable jTableVirtual;
    private javax.swing.JTextField jTextFilterOrder;
    private javax.swing.JTextField jTextSamplingRate;
    private javax.swing.JTextField jTextSamplingRate3;
    private javax.swing.JButton loadSignal;
    private javax.swing.JTextField lowCutoffFreqTextField;
    private javax.swing.JButton saveSignal;
    // End of variables declaration//GEN-END:variables

    public void addDiscreteSignal(DiscreteSignal loadSignal) {
        if (loadSignal != null) {
            disSignalContainer.add(loadSignal);
            discreteTableModel.fireTableDataChanged();
        }
    }
}
